version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-express-net
      - mongo-db-flask

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://root:toor@mongo:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mongo-express-net
  
  flask-app:
    build: 
      context: .
    container_name: flask-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongo-db-flask

networks:
  mongo-express-net: 
  mongo-db-flask:

volumes:
  mongo-data:
